### ISSUE TITLE
Random crash and failure of noisetorch and other conference software 

### ISSUE THREAD

**Issue by bahtioraliev** [lawl/NoiseTorch#145]
NoiseTorch crash after 1 or 2 sessions with zoom or slack conference.

Then it becomes completely imposable to bring it back to work. Sometimes, "playing" with sound settings the noisetorch working correctly. Following behavior causes the ubuntu setting and zoom to crash.

In some cases, I get "cannot load module-loopback pulseaudio" during reload and unload.

```
admin@pc:~/Redis-Enterprise$ systemctl --user status pulseaudio
● pulseaudio.service - Sound Service
     Loaded: loaded (/usr/lib/systemd/user/pulseaudio.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-05-31 14:13:28 IDT; 1h 8min ago
TriggeredBy: ● pulseaudio.socket
   Main PID: 1653 (pulseaudio)
     CGroup: /user.slice/user-1000.slice/user@1000.service/pulseaudio.service
             └─1653 /usr/bin/pulseaudio --daemonize=no --log-target=journal

May 31 14:14:55 tool pulseaudio[1653]: No remapping configured, proceeding nonetheless!
May 31 14:14:55 tool pulseaudio[1653]: Too many underruns, increasing latency to 12.00 ms
May 31 14:14:56 tool pulseaudio[1653]: Source minimum latency increased to 4.00 ms
May 31 14:14:56 tool pulseaudio[1653]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
May 31 14:15:05 tool pulseaudio[1653]: Too many underruns, increasing latency to 17.00 ms
May 31 14:18:46 tool pulseaudio[1653]: Source minimum latency increased to 8.00 ms
May 31 14:18:46 tool pulseaudio[1653]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
May 31 15:01:40 tool pulseaudio[1653]: Source minimum latency increased to 16.00 ms
May 31 15:01:40 tool pulseaudio[1653]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
May 31 15:02:15 tool pulseaudio[1653]: Too many underruns, increasing latency to 22.00 ms
```

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Linux tool 5.12.0-051200-generic x86_64 GNU/Linux

Log -

```
admin@pc:noisetorch -log
2021/05/31 15:28:15 Application starting. Version: 0.11.2 (official)
2021/05/31 15:28:15 CAP_SYS_RESOURCE: true
2021/05/31 15:28:15 Checking if config needs to be initialized
2021/05/31 15:28:15 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/admin1/.config'
2021/05/31 15:28:15 Wrote temp librnnoise to: /tmp/librnnoise-432674256.so
2021/05/31 15:28:15 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/admin1/.config'
2021/05/31 15:28:15 Audioserver package name: pulseaudio
2021/05/31 15:28:15 Audioserver package version: 13.99.1
2021/05/31 15:28:15 Detected PulseAudio
2021/05/31 15:28:15 Checking for updates
2021/05/31 15:28:15 Getting caps for: /home/admin1/.local/bin/noisetorch
2021/05/31 15:28:15 Audioserver package name: pulseaudio
2021/05/31 15:28:15 Audioserver package version: 13.99.1
2021/05/31 15:28:15 Detected PulseAudio
2021/05/31 15:28:15 Connected to audio server. Server name 'PulseAudio'
2021/05/31 15:28:15 Output alsa_output.usb-Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000-00.analog-stereo, {Index:0 Name:alsa_output.usb-Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000-00.analog-stereo Description:ThinkPad Thunderbolt 3 Dock USB Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:7 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.usb-Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000-00.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:182 PropList:map[alsa.card:2 alsa.card_name:ThinkPad Thunderbolt 3 Dock USB alsa.class:generic alsa.device:0 alsa.driver_name:snd_usb_audio alsa.id:USB Audio alsa.long_card_name:Lenovo ThinkPad Thunderbolt 3 Dock USB at usb-0000:08:00.0-2.1.1.2, full speed alsa.name:USB Audio alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:352800 device.buffering.fragment_size:176400 device.bus:usb device.bus_path:pci-0000:08:00.0-usb-0:2.1.1.2:1.0 device.class:sound device.description:ThinkPad Thunderbolt 3 Dock USB Audio Analog Stereo device.icon_name:audio-card-usb device.product.id:3083 device.product.name:ThinkPad Thunderbolt 3 Dock USB Audio device.profile.description:Analog Stereo device.profile.name:analog-stereo device.serial:Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000 device.string:front:2 device.vendor.id:17ef device.vendor.name:Lenovo module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/0000:04:01.0/0000:06:00.0/0000:07:02.0/0000:08:00.0/usb3/3-2/3-2.1/3-2.1.1/3-2.1.1.2/3-2.1.1.2:1.0/sound/card2 udev.id:usb-Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000-00] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-output Description:Analog Output Pririty:9900 Available:0}] ActivePortName:analog-output Formats:[{Encoding:1 PropList:map[]}]}
2021/05/31 15:28:15 Output alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink, {Index:1 Name:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink Description:sof-hda-dsp HDMI3/DP3 Output SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:3 MonitorSourceName:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_5__sink.monitor Latency:0 Driver:module-alsa-card.c Flags:166 PropList:map[alsa.card:0 alsa.card_name:sof-hda-dsp alsa.class:generic alsa.device:5 alsa.driver_name:snd_soc_skl_hda_dsp alsa.id:HDMI3 (*) alsa.long_card_name:sof-hda-dsp alsa.mixer_device:hw:sofhdadsp alsa.name: alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:65536 device.buffering.fragment_size:16384 device.bus:pci device.bus_path:pci-0000:00:1f.3-platform-skl_hda_dsp_generic device.class:sound device.description:sof-hda-dsp HDMI3/DP3 Output device.icon_name:audio-card-pci device.product.id:02c8 device.profile.description:HDMI3/DP3 Output device.profile.name:HiFi: hw:sofhdadsp,5: sink device.string:hw:sofhdadsp,5 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:2 Ports:[{Name:[Out] HDMI3 Description:HDMI3/DP3 Output Pririty:700 Available:1}] ActivePortName:[Out] HDMI3 Formats:[{Encoding:1 PropList:map[]}]}
2021/05/31 15:28:15 Output alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink, {Index:2 Name:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink Description:sof-hda-dsp HDMI2/DP2 Output SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:4 MonitorSourceName:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink.monitor Latency:0 Driver:module-alsa-card.c Flags:166 PropList:map[alsa.card:0 alsa.card_name:sof-hda-dsp alsa.class:generic alsa.device:4 alsa.driver_name:snd_soc_skl_hda_dsp alsa.id:HDMI2 (*) alsa.long_card_name:sof-hda-dsp alsa.mixer_device:hw:sofhdadsp alsa.name: alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:65536 device.buffering.fragment_size:16384 device.bus:pci device.bus_path:pci-0000:00:1f.3-platform-skl_hda_dsp_generic device.class:sound device.description:sof-hda-dsp HDMI2/DP2 Output device.icon_name:audio-card-pci device.product.id:02c8 device.profile.description:HDMI2/DP2 Output device.profile.name:HiFi: hw:sofhdadsp,4: sink device.string:hw:sofhdadsp,4 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:2 Ports:[{Name:[Out] HDMI2 Description:HDMI2/DP2 Output Pririty:600 Available:1}] ActivePortName:[Out] HDMI2 Formats:[{Encoding:1 PropList:map[]}]}
2021/05/31 15:28:15 Output alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink, {Index:3 Name:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink Description:sof-hda-dsp HDMI1/DP1 Output SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:5 MonitorSourceName:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink.monitor Latency:0 Driver:module-alsa-card.c Flags:166 PropList:map[alsa.card:0 alsa.card_name:sof-hda-dsp alsa.class:generic alsa.device:3 alsa.driver_name:snd_soc_skl_hda_dsp alsa.id:HDMI1 (*) alsa.long_card_name:sof-hda-dsp alsa.mixer_device:hw:sofhdadsp alsa.name: alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:65536 device.buffering.fragment_size:16384 device.bus:pci device.bus_path:pci-0000:00:1f.3-platform-skl_hda_dsp_generic device.class:sound device.description:sof-hda-dsp HDMI1/DP1 Output device.icon_name:audio-card-pci device.product.id:02c8 device.profile.description:HDMI1/DP1 Output device.profile.name:HiFi: hw:sofhdadsp,3: sink device.string:hw:sofhdadsp,3 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:2 Ports:[{Name:[Out] HDMI1 Description:HDMI1/DP1 Output Pririty:500 Available:2}] ActivePortName:[Out] HDMI1 Formats:[{Encoding:1 PropList:map[]}]}
2021/05/31 15:28:15 Output alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink, {Index:4 Name:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink Description:sof-hda-dsp Speaker + Headphones SampleSpec:{Format:3 Channels:2 Rate:48000} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:6 MonitorSourceName:alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink.monitor Latency:0 Driver:module-alsa-card.c Flags:183 PropList:map[alsa.card:0 alsa.card_name:sof-hda-dsp alsa.class:generic alsa.device:0 alsa.driver_name:snd_soc_skl_hda_dsp alsa.id:HDA Analog (*) alsa.long_card_name:sof-hda-dsp alsa.mixer_device:hw:sofhdadsp alsa.name: alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:65536 device.buffering.fragment_size:16384 device.bus:pci device.bus_path:pci-0000:00:1f.3-platform-skl_hda_dsp_generic device.class:sound device.description:sof-hda-dsp Speaker + Headphones device.icon_name:audio-card-pci device.product.id:02c8 device.profile.description:Speaker + Headphones device.profile.name:HiFi: hw:sofhdadsp: sink device.string:hw:sofhdadsp device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:2 Ports:[{Name:[Out] Speaker Description:Speaker Pririty:100 Available:0} {Name:[Out] Headphones Description:Headphones Pririty:200 Available:1}] ActivePortName:[Out] Speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/05/31 15:28:20 Querying pulse rlimit
2021/05/31 15:28:20 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2021/05/31 15:28:20 Rlimit: {Cur:18446744073709551615 Max:18446744073709551615}
2021/05/31 15:28:20 Loading supressor for pulse
2021/05/31 15:28:20 Loaded null sink as idx: 25
2021/05/31 15:28:20 Loaded ladspa sink as idx: 26
2021/05/31 15:28:20 Loaded loopback as idx: 27
2021/05/31 15:28:20 Loaded remap source as idx: 28
2021/05/31 15:28:20 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/admin1/.config'
2021/05/31 15:28:26 Unloading modules for pulseaudio
2021/05/31 15:28:26 Trying to remove rlimit. Limit is: {Cur:200000 Max:200000}
2021/05/31 15:28:26 Rlimit: {Cur:18446744073709551615 Max:18446744073709551615}
2021/05/31 15:28:26 Searching for null-sink
2021/05/31 15:28:26 Found null-sink at id [25], sending unload command
2021/05/31 15:28:26 Searching for ladspa-sink
2021/05/31 15:28:26 PulseAudio client was closed
2021/05/31 15:28:26 Querying pulse rlimit
2021/05/31 15:28:26 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2021/05/31 15:28:26 Rlimit: {Cur:18446744073709551615 Max:18446744073709551615}
2021/05/31 15:28:26 Loading supressor for pulse
2021/05/31 15:28:27 Couldn't create pulseaudio client: dial unix /run/user/1000/pulse/native: connect: resource temporarily unavailable
Couldn't create pulseaudio client: dial unix /run/user/1000/pulse/native: connect: resource temporarily unavailable
2021/05/31 15:28:27 Couldn't fetch pulse server info: connection closed
Couldn't fetch pulse server info: connection closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74e0cd]

goroutine 24 [running]:
main.serverInfo(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/code/NoiseTorch/main.go:221 +0x18d
main.paConnectionWatchdog(0xc000172000)
	/home/user/code/NoiseTorch/main.go:193 +0x1d0
created by main.main
	/home/user/code/NoiseTorch/main.go:88 +0x48f
```

**Comment by lawl** [comment]
This looks like pulseaudio is crashing. Can you check the pulseaudio logs if you see a crash? If not, can you start pulseaudio from a terminal instead of as a systemd service to reproduce this?

**Comment by lawl** [comment]
unresponsive
